import { Sparkles, PiggyBank, Landmark, TrendingUp } from 'lucide-react'
import { PageHeader } from '../../components/layout/PageHeader'
import { Card } from '../../components/ui/Card'
import { Badge } from '../../components/ui/Badge'
import { ProgressBar } from '../../components/ui/ProgressBar'

function AiBadge() {
  return <Badge tone="brand" className="!bg-violet-50 !text-violet-700">✨ AI Insight</Badge>
}

export function FinancialAdvisor() {
  const score = 742
  const scoreMax = 900
  const scorePct = Math.round((score / scoreMax) * 100)

  return (
    <div className="pb-6">
      <PageHeader title="Financial Advisor" subtitle="AI-powered insights on your finances" />

      <div className="px-4 mt-2">
        <Card className="bg-gradient-to-br from-violet-600 to-violet-500 text-white">
          <div className="flex items-center justify-between">
            <p className="text-xs font-medium text-white/75">Your Credit Score</p>
            <AiBadge />
          </div>
          <div className="flex items-end gap-2 mt-2">
            <p className="text-4xl font-bold font-display">{score}</p>
            <p className="text-sm text-white/75 mb-1">/ {scoreMax}</p>
          </div>
          <Badge tone="success" className="mt-1">Good</Badge>
          <div className="mt-4">
            <div className="h-2.5 w-full rounded-full bg-white/20 overflow-hidden">
              <div className="h-full rounded-full bg-gold-400" style={{ width: `${scorePct}%` }} />
            </div>
            <p className="mt-1.5 text-[11px] text-white/70">Based on savings regularity, repayment history & attendance</p>
          </div>
        </Card>
      </div>

      <div className="px-4 mt-5">
        <div className="flex items-center justify-between mb-2">
          <p className="text-[15px] font-bold text-ink-900 font-display">Savings Recommendation</p>
          <AiBadge />
        </div>
        <Card className="flex items-start gap-3">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-brand-600">
            <PiggyBank className="h-5 w-5" />
          </div>
          <div className="min-w-0">
            <p className="text-sm font-semibold text-ink-900">Increase weekly savings by ₹100</p>
            <p className="text-xs text-ink-500 mt-1 leading-relaxed">
              Based on your income pattern, saving ₹600/week instead of ₹500 could grow your corpus by an extra
              ₹5,200 this year, improving your loan eligibility.
            </p>
          </div>
        </Card>
      </div>

      <div className="px-4 mt-5">
        <div className="flex items-center justify-between mb-2">
          <p className="text-[15px] font-bold text-ink-900 font-display">Loan Eligibility Prediction</p>
          <AiBadge />
        </div>
        <Card className="flex items-start gap-3">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gold-50 text-gold-600">
            <Landmark className="h-5 w-5" />
          </div>
          <div className="min-w-0 flex-1">
            <p className="text-sm font-semibold text-ink-900">Eligible up to ₹35,000</p>
            <p className="text-xs text-ink-500 mt-1 leading-relaxed">
              Based on your repayment history, current savings and SHG grading, you are likely eligible for a
              higher loan amount than your last application.
            </p>
            <ProgressBar value={22000} max={35000} tone="gold" className="mt-3" />
            <p className="mt-1 text-[11px] text-ink-400">₹22,000 outstanding of ₹35,000 predicted limit</p>
          </div>
        </Card>
      </div>

      <div className="px-4 mt-5">
        <div className="flex items-center justify-between mb-2">
          <p className="text-[15px] font-bold text-ink-900 font-display">Spending Trend</p>
          <AiBadge />
        </div>
        <Card className="flex items-start gap-3">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-sky-50 text-sky-600">
            <TrendingUp className="h-5 w-5" />
          </div>
          <div className="min-w-0">
            <p className="text-sm font-semibold text-ink-900">Your savings grew 18% year-on-year</p>
            <p className="text-xs text-ink-500 mt-1 leading-relaxed">
              You're saving more consistently than 82% of members in your SHG. Keep it up to unlock better loan terms.
            </p>
          </div>
        </Card>
      </div>

      <div className="px-4 mt-5">
        <Card className="flex items-center gap-2 bg-ink-50 border-dashed">
          <Sparkles className="h-4 w-4 text-violet-500 shrink-0" />
          <p className="text-[11px] text-ink-500 leading-relaxed">
            These insights are generated by AI based on historical data and are indicative only. Please consult your
            SHG leader for final decisions.
          </p>
        </Card>
      </div>
    </div>
  )
}
