name: shg_saathi
description: "NavaSakhi — AI-Enabled Digital Platform for Self-Help Groups and Women-Led Microenterprises"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  provider: ^6.1.2
  fl_chart: ^0.69.2
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  supabase_flutter: ^2.8.0
  mobile_scanner: ^5.2.3
  http: ^1.2.0
  sentry_flutter: ^8.14.2
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.0
  file_picker: ^8.1.6
  url_launcher: ^6.3.1
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^22.1.0
  timezone: ^0.11.1
  flutter_timezone: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
