-- Gap-hunt round 192 (iteration 19): AI Advisor modules fresh audit found
-- `ai_advisor_logs_insert_self` (0002) checks only `member_id = auth.uid()`
-- — never restricting `blocked`/`block_reason`/`response`. Migration 0044
-- added those two columns and reasoned "row-level policies apply to the
-- whole row... no new client-facing INSERT path is opened," which is true
-- but incomplete: it never tightened the EXISTING check to restrict what
-- values a client-originated row can carry. Any signed-in member could
-- insert her own real member_id with an arbitrary `response` (never
-- actually generated by Groq) and `blocked: true`/`block_reason: <any
-- text>` — directly corrupting `AdminRepository.fetchAiAdvisorModerationStats()`,
-- which counts `blocked=true` rows verbatim for the Admin Monitoring "AI
-- Advisor Blocks (7d)" stat, and plants a fabricated "the AI told me X"
-- transcript staff would otherwise trust (staff SELECT access is
-- unconditional per `ai_advisor_logs_select_self_or_staff`).
--
-- The real "blocked" row insert already happens entirely server-side:
-- `supabase/functions/ai-advisor-proxy/index.ts` uses a SERVICE_ROLE_KEY
-- client (bypasses RLS) to log a rejected attempt — the client-facing
-- Dart repository (`AiAdvisorRepository.ask()`) never sets `blocked`/
-- `block_reason` at all, relying on their `false`/`null` column defaults.
-- Tightening the client-facing policy to require exactly that shape is
-- therefore a no-op for every legitimate insert path and closes the gap
-- for the illegitimate one.

drop policy if exists "ai_advisor_logs_insert_self" on public.ai_advisor_logs;

create policy "ai_advisor_logs_insert_self" on public.ai_advisor_logs
  for insert with check (
    member_id = auth.uid()
    and blocked = false
    and block_reason is null
  );
